/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './src/renderer/index.html',
    './src/renderer/src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {},
  },
  plugins: [
    require('daisyui'),
  ],
  daisyui: {
    themes: [
      {
        flexokilight: {
          'color-scheme': 'light',
          'primary': '#205EA6',
          'primary-content': '#FFFCF0',
          'secondary': '#5E409D',
          'secondary-content': '#FFFCF0',
          'accent': '#24837B',
          'accent-content': '#FFFCF0',
          'neutral': '#6F6E69',
          'neutral-content': '#E6E4D9',
          'base-100': '#FFFCF0',
          'base-200': '#F2F0E5',
          'base-300': '#E6E4D9',
          'base-content': '#100F0F',
          'info': '#205EA6',
          'info-content': '#FFFCF0',
          'success': '#66800B',
          'success-content': '#FFFCF0',
          'warning': '#AD8301',
          'warning-content': '#100F0F',
          'error': '#AF3029',
          'error-content': '#FFFCF0',
        },
      },
      {
        flexokidark: {
          'color-scheme': 'dark',
          'primary': '#4385BE',
          'primary-content': '#100F0F',
          'secondary': '#8B7EC8',
          'secondary-content': '#100F0F',
          'accent': '#3AA99F',
          'accent-content': '#100F0F',
          'neutral': '#878580',
          'neutral-content': '#E6E4D9',
          'base-100': '#100F0F',
          'base-200': '#1C1B1A',
          'base-300': '#282726',
          'base-content': '#E6E4D9',
          'info': '#4385BE',
          'info-content': '#100F0F',
          'success': '#879A39',
          'success-content': '#100F0F',
          'warning': '#D0A215',
          'warning-content': '#100F0F',
          'error': '#D14D41',
          'error-content': '#100F0F',
        },
      },
    ],
  },
}
